[package]
name = "aoc-cli"
description = "Advent of Code command-line helper tool"
version = "0.5.1"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
categories = ["command-line-utilities"]
edition = "2021"
repository = "https://github.com/scarvalhojr/aoc-cli"
documentation = "https://docs.rs/crate/aoc-cli/latest"
readme = "README.md"
license = "MIT"

[[bin]]
name = "aoc"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["color", "derive"]}
home = "0.5"
html2text = "0.4"
regex = "1.7"
reqwest = { version = "0.11", features = ["blocking"] }
term_size = "0.3"
html2md = "0.2"

# Use static linking of OpenSSL on Linux with MUSL
[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }