[package]
name = "aoc-cli"
description = "Advent of Code command-line helper tool"
version = "0.3.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2021"
repository = "https://github.com/scarvalhojr/aoc-cli"
readme = "README.md"
license = "MIT"

[[bin]]
name = "aoc"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = "2.34"
home = "0.5"
html2text = "0.2"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking"] }
term_size = "0.3"
