name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    # Ensure committed Cargo.lock is up to date
    - name: Check Cargo.lock
      run: git diff --exit-code -- Cargo.lock

    - name: Run tests
      run: cargo test --verbose
