name: Clippy and format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-and-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --verbose
      - name: Check formatting
        run: cargo fmt --check --verbose
