name: Windows Release

on:
  push:
    branches: [ "main" ]

jobs:
  publish-windows:
    name: Update Windows Package Manager repository
    runs-on: windows-latest
    environment: Release
    variables:
      release-version: '0.4.7'
      package-url: "https://github.com/scarvalhojr/aoc-cli/releases/download/$(release-version)/aoc-cli-$(release-version)-x86_64.msi"
    steps:
      - name: Run wingetcreate
        shell: powershell
        run: |
          # iwr https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile $(vcLibsBundleFile)
          # Add-AppxPackage $(vcLibsBundleFile)

          # Download, install, and execute update.
          # iwr https://aka.ms/wingetcreate/latest/msixbundle -OutFile $(appxBundleFile)
          # Add-AppxPackage $(appxBundleFile)

          wingetcreate update scarvalhojr.aoc-cli -urls $(package-url) -version $(release-version) --token $(GH_ACCESS_TOKEN) --submit
